version: "3.8"

services:
  http-server:
    build:
      context: .
      dockerfile: apps/http-server/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3001"

  ws-server:
    build:
      context: .
      dockerfile: apps/ws-server/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3002:3002"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - http-server
      - ws-server
